version: "3.7"

services:
  database_rent:
    image: postgres
    container_name: database_rent
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rentacar
    volumes:
      - pgdata:/data/postgres
  
  app:
    build: .
    container_name: rentacar
    ports: 
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - database_rent
    depends_on:
      - database_rent

volumes:
  pgdata:
    driver: local